// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PapaMobileX.Server.DataSource;

#nullable disable

namespace PapaMobileX.Server.DataSource.Migrations
{
    [DbContext(typeof(CommonContext))]
    [Migration("20220526191038_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("PapaMobileX.Server.DataSource.Models.Account", b =>
                {
                    b.Property<Guid>("AccountGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountGuid");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PapaMobileX.Server.DataSource.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AccountGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClaimId");

                    b.HasIndex("AccountGuid");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("PapaMobileX.Server.DataSource.Models.Claim", b =>
                {
                    b.HasOne("PapaMobileX.Server.DataSource.Models.Account", null)
                        .WithMany("Claims")
                        .HasForeignKey("AccountGuid");
                });

            modelBuilder.Entity("PapaMobileX.Server.DataSource.Models.Account", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
