//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaMobileX.App.BusinessLogic.ResourceDictionary {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PapaMobileX.App.BusinessLogic.ResourceDictionary.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string LetsRide {
            get {
                return ResourceManager.GetString("LetsRide", resourceCulture);
            }
        }
        
        public static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string InvalidUriLoginError {
            get {
                return ResourceManager.GetString("InvalidUriLoginError", resourceCulture);
            }
        }
        
        public static string ServerNotFoundLoginError {
            get {
                return ResourceManager.GetString("ServerNotFoundLoginError", resourceCulture);
            }
        }
        
        public static string InvalidCredentialsLoginError {
            get {
                return ResourceManager.GetString("InvalidCredentialsLoginError", resourceCulture);
            }
        }
        
        public static string TimeoutLoginError {
            get {
                return ResourceManager.GetString("TimeoutLoginError", resourceCulture);
            }
        }
        
        public static string OtherLoginError {
            get {
                return ResourceManager.GetString("OtherLoginError", resourceCulture);
            }
        }
    }
}
